Repository Sparata-Sheep/SheepEz_loan, pull requests merged in 2024-10, with the labels that each got.

#8 feat: craete lawyer module & define entity and domain
  lawyer/lawyer-api/build.gradle
  lawyer/lawyer-api/src/main/java/com/sheep/ezloan/LawyerApiApplication.java
  lawyer/lawyer-api/src/main/java/com/sheep/ezloan/lawyer/api/controller/LawyerController.java
  lawyer/lawyer-api/src/main/resources/application.yml
  lawyer/lawyer-api/src/test/java/com/sheep/ezloan/ContextTest.java
  lawyer/lawyer-api/src/test/java/com/sheep/ezloan/DevelopTest.java
  lawyer/lawyer-api/src/test/java/com/sheep/ezloan/LawyerApplicationTest.java
  lawyer/lawyer-domain/build.gradle
  lawyer/lawyer-domain/src/main/java/com/sheep/ezloan/lawyer/doamin/model/Lawyer.java
  lawyer/lawyer-domain/src/main/java/com/sheep/ezloan/lawyer/doamin/repository/LawyerRepository.java
  lawyer/lawyer-domain/src/main/java/com/sheep/ezloan/lawyer/doamin/service/LawyerService.java
  lawyer/lawyer-domain/src/main/resources/lawyer-domain.yml
  lawyer/lawyer-domain/src/test/java/com/sheep/lzloan/lawyer/doamin/LawyerServiceTest.java
  lawyer/lawyer-storage/build.gradle
  lawyer/lawyer-storage/src/main/java/com/sheep/ezloan/lawyer/storage/config/CoreDataSourceConfig.java
  lawyer/lawyer-storage/src/main/java/com/sheep/ezloan/lawyer/storage/config/CoreJpaConfig.java
  lawyer/lawyer-storage/src/main/java/com/sheep/ezloan/lawyer/storage/config/CoreQueryDslConfig.java
  lawyer/lawyer-storage/src/main/java/com/sheep/ezloan/lawyer/storage/entity/LawyerEntity.java
  lawyer/lawyer-storage/src/main/java/com/sheep/ezloan/lawyer/storage/implement/LawyerJpaRepository.java
  lawyer/lawyer-storage/src/main/java/com/sheep/ezloan/lawyer/storage/implement/LawyerRepositoryAdapter.java
  lawyer/lawyer-storage/src/main/resources/lawyer-storage.yml
  lawyer/lawyer-storage/src/test/java/com/sheep/ezloan/lawyer/storage/CoreDbContextTest.java
  lawyer/lawyer-storage/src/test/java/com/sheep/ezloan/lawyer/storage/CoreDbTestApplication.java
  lawyer/lawyer-storage/src/test/resources/application.yml
  settings.gradle
Labels: feat, setting

#9 feat: create contact module & implement basic CRUD + Seacrh of Post domain
  contact/contact-api/build.gradle
  contact/contact-api/src/main/java/com/sheep/ezloan/ContactApiApplication.java
  contact/contact-api/src/main/java/com/sheep/ezloan/contact/api/controller/PostController.java
  contact/contact-api/src/main/java/com/sheep/ezloan/contact/api/controller/dto/PostDto.java
  contact/contact-api/src/main/resources/application.yml
  contact/contact-api/src/test/java/com/sheep/ezloan/contact/api/ContactApiApplicationTests.java
  contact/contact-domain/build.gradle
  contact/contact-domain/src/main/java/com/sheep/ezloan/contact/domain/model/LoanType.java
  contact/contact-domain/src/main/java/com/sheep/ezloan/contact/domain/model/Post.java
  contact/contact-domain/src/main/java/com/sheep/ezloan/contact/domain/model/PostResult.java
  contact/contact-domain/src/main/java/com/sheep/ezloan/contact/domain/model/PostStatus.java
  contact/contact-domain/src/main/java/com/sheep/ezloan/contact/domain/repository/PostRepository.java
  contact/contact-domain/src/main/java/com/sheep/ezloan/contact/domain/service/PostService.java
  contact/contact-domain/src/main/resources/application.yml
  contact/contact-storage/build.gradle
  contact/contact-storage/src/main/java/com/sheep/ezloan/contact/storage/config/CoreDataSourceConfig.java
  contact/contact-storage/src/main/java/com/sheep/ezloan/contact/storage/config/CoreJpaConfig.java
  contact/contact-storage/src/main/java/com/sheep/ezloan/contact/storage/config/CoreQueryDslConfig.java
  contact/contact-storage/src/main/java/com/sheep/ezloan/contact/storage/custom/PostRepositoryCustom.java
  contact/contact-storage/src/main/java/com/sheep/ezloan/contact/storage/entity/PostEntity.java
  contact/contact-storage/src/main/java/com/sheep/ezloan/contact/storage/implement/PostJpaRepository.java
  contact/contact-storage/src/main/java/com/sheep/ezloan/contact/storage/implement/PostRepositoryAdapter.java
  contact/contact-storage/src/main/java/com/sheep/ezloan/contact/storage/implement/PostRepositoryImpl.java
  contact/contact-storage/src/main/resources/contact-storage.yml
  contact/contact-storage/src/test/resources/application.yml
  settings.gradle
Labels: feat, setting

#12 feat: 변호사 CRUD
  example/example-storage/src/main/java/com/sheep/ezloan/example/storage/config/CoreDataSourceConfig.java
  lawyer/lawyer-api/src/main/java/com/sheep/ezloan/lawyer/api/controller/LawyerController.java
  lawyer/lawyer-api/src/main/java/com/sheep/ezloan/lawyer/api/dto/CreateLawyerRequestDto.java
  lawyer/lawyer-api/src/main/java/com/sheep/ezloan/lawyer/api/dto/LawyerResponse.java
  lawyer/lawyer-api/src/main/java/com/sheep/ezloan/lawyer/api/dto/ModifyLawyerRequestDto.java
  lawyer/lawyer-api/src/main/resources/application.yml
  lawyer/lawyer-domain/build.gradle
  lawyer/lawyer-domain/src/main/java/com/sheep/ezloan/lawyer/doamin/repository/LawyerRepository.java
  lawyer/lawyer-domain/src/main/java/com/sheep/ezloan/lawyer/doamin/service/LawyerService.java
  lawyer/lawyer-domain/src/main/java/com/sheep/ezloan/lawyer/domain/model/Lawyer.java
  lawyer/lawyer-domain/src/main/java/com/sheep/ezloan/lawyer/domain/repository/LawyerRepository.java
  lawyer/lawyer-domain/src/main/java/com/sheep/ezloan/lawyer/domain/service/LawyerService.java
  lawyer/lawyer-domain/src/test/java/com/sheep/ezloan/lawyer/domain/LawyerServiceTest.java
  lawyer/lawyer-domain/src/test/java/com/sheep/lzloan/lawyer/doamin/LawyerServiceTest.java
  lawyer/lawyer-storage/src/main/java/com/sheep/ezloan/lawyer/storage/config/CoreDataSourceConfig.java
  lawyer/lawyer-storage/src/main/java/com/sheep/ezloan/lawyer/storage/config/CoreJpaConfig.java
  lawyer/lawyer-storage/src/main/java/com/sheep/ezloan/lawyer/storage/entity/LawyerEntity.java
  lawyer/lawyer-storage/src/main/java/com/sheep/ezloan/lawyer/storage/implement/LawyerCustomRepository.java
  lawyer/lawyer-storage/src/main/java/com/sheep/ezloan/lawyer/storage/implement/LawyerJpaRepository.java
  lawyer/lawyer-storage/src/main/java/com/sheep/ezloan/lawyer/storage/implement/LawyerJpaRepositoryImpl.java
  lawyer/lawyer-storage/src/main/java/com/sheep/ezloan/lawyer/storage/implement/LawyerRepositoryAdapter.java
  support/support-storage/src/main/java/com/sheep/ezloan/support/entity/BaseEntity.java
Labels: feat

#14 Feat implement basic crud+seach of contract
  contact/contact-api/src/main/java/com/sheep/ezloan/contact/api/controller/ContractController.java
  contact/contact-api/src/main/java/com/sheep/ezloan/contact/api/controller/dto/ContractDto.java
  contact/contact-domain/src/main/java/com/sheep/ezloan/contact/domain/model/Contract.java
  contact/contact-domain/src/main/java/com/sheep/ezloan/contact/domain/model/ContractResult.java
  contact/contact-domain/src/main/java/com/sheep/ezloan/contact/domain/model/ContractStatus.java
  contact/contact-domain/src/main/java/com/sheep/ezloan/contact/domain/repository/ContractRepository.java
  contact/contact-domain/src/main/java/com/sheep/ezloan/contact/domain/service/ContractService.java
  contact/contact-storage/src/main/java/com/sheep/ezloan/contact/storage/custom/ContractRepositoryCustom.java
  contact/contact-storage/src/main/java/com/sheep/ezloan/contact/storage/entity/ContractEntity.java
  contact/contact-storage/src/main/java/com/sheep/ezloan/contact/storage/implement/ContractJpaRepository.java
  contact/contact-storage/src/main/java/com/sheep/ezloan/contact/storage/implement/ContractRepositoryAdapter.java
  contact/contact-storage/src/main/java/com/sheep/ezloan/contact/storage/implement/ContractRepositoryImpl.java
  support/support-api/src/main/java/com/sheep/ezloan/support/error/ErrorCode.java
  support/support-api/src/main/java/com/sheep/ezloan/support/error/ErrorType.java
Labels: feat

#18 feat: 리뷰 CRUD
  lawyer/lawyer-api/src/main/java/com/sheep/ezloan/lawyer/api/controller/ReviewController.java
  lawyer/lawyer-api/src/main/java/com/sheep/ezloan/lawyer/api/dto/CreateReviewRequestDto.java
  lawyer/lawyer-api/src/main/java/com/sheep/ezloan/lawyer/api/dto/ModifyReviewRequestDto.java
  lawyer/lawyer-api/src/main/java/com/sheep/ezloan/lawyer/api/dto/ReviewResponse.java
  lawyer/lawyer-domain/src/main/java/com/sheep/ezloan/lawyer/domain/model/Lawyer.java
  lawyer/lawyer-domain/src/main/java/com/sheep/ezloan/lawyer/domain/model/Review.java
  lawyer/lawyer-domain/src/main/java/com/sheep/ezloan/lawyer/domain/repository/ReviewRepository.java
  lawyer/lawyer-domain/src/main/java/com/sheep/ezloan/lawyer/domain/service/ReviewService.java
  lawyer/lawyer-domain/src/test/java/com/sheep/ezloan/lawyer/domain/ReviewServiceTest.java
  lawyer/lawyer-storage/src/main/java/com/sheep/ezloan/lawyer/storage/entity/LawyerEntity.java
  lawyer/lawyer-storage/src/main/java/com/sheep/ezloan/lawyer/storage/entity/ReviewEntity.java
  lawyer/lawyer-storage/src/main/java/com/sheep/ezloan/lawyer/storage/implement/ReviewCustomRepository.java
  lawyer/lawyer-storage/src/main/java/com/sheep/ezloan/lawyer/storage/implement/ReviewJpaRepository.java
  lawyer/lawyer-storage/src/main/java/com/sheep/ezloan/lawyer/storage/implement/ReviewJpaRepositoryImpl.java
  lawyer/lawyer-storage/src/main/java/com/sheep/ezloan/lawyer/storage/implement/ReviewRepositoryAdapter.java
Labels: feat

#19 Feat: implement of additional features for contact app
  contact/contact-api/build.gradle
  contact/contact-api/src/main/java/com/sheep/ezloan/contact/api/controller/ContractController.java
  contact/contact-api/src/main/java/com/sheep/ezloan/contact/api/controller/PostController.java
  contact/contact-api/src/main/java/com/sheep/ezloan/contact/api/controller/dto/ContractDto.java
  contact/contact-api/src/main/java/com/sheep/ezloan/contact/api/controller/dto/PostDto.java
  contact/contact-domain/build.gradle
  contact/contact-domain/src/main/java/com/sheep/ezloan/contact/domain/repository/ContractRepository.java
  contact/contact-domain/src/main/java/com/sheep/ezloan/contact/domain/repository/PostRepository.java
  contact/contact-domain/src/main/java/com/sheep/ezloan/contact/domain/service/ContractService.java
  contact/contact-domain/src/main/java/com/sheep/ezloan/contact/domain/service/PostService.java
  contact/contact-storage/src/main/java/com/sheep/ezloan/contact/storage/entity/PostEntity.java
  contact/contact-storage/src/main/java/com/sheep/ezloan/contact/storage/implement/ContractJpaRepository.java
  contact/contact-storage/src/main/java/com/sheep/ezloan/contact/storage/implement/ContractRepositoryAdapter.java
  contact/contact-storage/src/main/java/com/sheep/ezloan/contact/storage/implement/ContractRepositoryImpl.java
  contact/contact-storage/src/main/java/com/sheep/ezloan/contact/storage/implement/PostJpaRepository.java
  contact/contact-storage/src/main/java/com/sheep/ezloan/contact/storage/implement/PostRepositoryAdapter.java
  contact/contact-storage/src/main/java/com/sheep/ezloan/contact/storage/implement/PostRepositoryImpl.java
  settings.gradle
  support/error/build.gradle
  support/error/src/main/java/com/sheep/ezloan/support/error/CoreApiException.java
  support/error/src/main/java/com/sheep/ezloan/support/error/ErrorCode.java
  support/error/src/main/java/com/sheep/ezloan/support/error/ErrorMessage.java
  support/error/src/main/java/com/sheep/ezloan/support/error/ErrorType.java
  support/support-api/build.gradle
  support/support-api/src/main/java/com/sheep/ezloan/support/error/ErrorType.java
  support/support-storage/src/main/java/com/sheep/ezloan/support/entity/BaseEntity.java
Labels: feat

#27 fix: cannot run lawyer application
  lawyer/lawyer-api/build.gradle
  lawyer/lawyer-api/src/main/resources/application.yml
Labels: bug

#41 feat: Contact App 권한 관리
  cloud/gateway/src/main/resources/application.yml
  contact/contact-api/src/main/java/com/sheep/ezloan/contact/api/controller/ContractController.java
  contact/contact-api/src/main/java/com/sheep/ezloan/contact/api/controller/PostController.java
  contact/contact-api/src/main/java/com/sheep/ezloan/contact/api/controller/dto/ContractDto.java
  contact/contact-api/src/main/resources/application.yml
  contact/contact-domain/src/main/java/com/sheep/ezloan/contact/domain/repository/ContractRepository.java
  contact/contact-domain/src/main/java/com/sheep/ezloan/contact/domain/service/ContractService.java
  contact/contact-domain/src/main/java/com/sheep/ezloan/contact/domain/service/PostService.java
  contact/contact-storage/src/main/java/com/sheep/ezloan/contact/storage/custom/ContractRepositoryCustom.java
  contact/contact-storage/src/main/java/com/sheep/ezloan/contact/storage/implement/ContractRepositoryAdapter.java
  contact/contact-storage/src/main/java/com/sheep/ezloan/contact/storage/implement/ContractRepositoryImpl.java
Labels: enhancement, feat

#45 feat: local docker compose setting
  clients/client-user/src/main/resources/client-user.yml
  cloud/auth/src/main/resources/application.yml
  cloud/eureka/src/main/resources/application.yml
  cloud/gateway/src/main/resources/application.yml
  contact/contact-api/src/main/resources/application.yml
  contact/contact-storage/src/main/resources/contact-storage.yml
  lawyer/lawyer-api/src/main/resources/application.yml
  lawyer/lawyer-api/src/test/java/com/sheep/ezloan/ContextTest.java
  lawyer/lawyer-api/src/test/java/com/sheep/ezloan/DevelopTest.java
  lawyer/lawyer-api/src/test/java/com/sheep/ezloan/LawyerApplicationTest.java
  lawyer/lawyer-storage/src/main/java/com/sheep/ezloan/lawyer/storage/config/CoreDataSourceConfig.java
  lawyer/lawyer-storage/src/main/resources/lawyer-storage.yml
  support/support-redis/src/main/resources/redis.yml
  user/user-api/src/main/resources/application.yml
  user/user-storage/src/main/resources/user-storage.yml
Labels: setting

#49 fix: signup
  support/support-authentication/src/main/java/com/sheep/ezloan/support/authentication/security/AuthorityMapperConfig.java
  support/support-authentication/src/main/java/com/sheep/ezloan/support/authentication/security/RoleHierarchyConfig.java
  support/support-authentication/src/main/java/com/sheep/ezloan/support/authentication/security/SecurityConfig.java
  support/support-authentication/src/main/java/com/sheep/ezloan/support/authentication/security/SecurityUtil.java
  support/support-authentication/src/main/java/com/sheep/ezloan/support/authentication/security/filter/CustomAuthenticationFilter.java
  user/user-api/src/main/java/com/sheep/ezloan/user/api/ClientController.java
  user/user-api/src/main/java/com/sheep/ezloan/user/api/UserController.java
Labels: bug

#51 fix: lawyer logic
  lawyer/lawyer-api/build.gradle
  lawyer/lawyer-api/src/main/java/com/sheep/ezloan/lawyer/api/controller/LawyerController.java
  lawyer/lawyer-api/src/main/java/com/sheep/ezloan/lawyer/api/dto/CreateLawyerRequestDto.java
  lawyer/lawyer-api/src/main/java/com/sheep/ezloan/lawyer/api/dto/LawyerResponse.java
  lawyer/lawyer-domain/src/main/java/com/sheep/ezloan/lawyer/domain/model/Lawyer.java
  lawyer/lawyer-domain/src/main/java/com/sheep/ezloan/lawyer/domain/repository/LawyerRepository.java
  lawyer/lawyer-domain/src/main/java/com/sheep/ezloan/lawyer/domain/service/LawyerService.java
  lawyer/lawyer-domain/src/test/java/com/sheep/ezloan/lawyer/domain/LawyerServiceTest.java
  lawyer/lawyer-storage/src/main/java/com/sheep/ezloan/lawyer/storage/entity/LawyerEntity.java
  lawyer/lawyer-storage/src/main/java/com/sheep/ezloan/lawyer/storage/implement/LawyerCustomRepository.java
  lawyer/lawyer-storage/src/main/java/com/sheep/ezloan/lawyer/storage/implement/LawyerJpaRepository.java
  lawyer/lawyer-storage/src/main/java/com/sheep/ezloan/lawyer/storage/implement/LawyerJpaRepositoryImpl.java
  lawyer/lawyer-storage/src/main/java/com/sheep/ezloan/lawyer/storage/implement/LawyerRepositoryAdapter.java
  lawyer/lawyer-storage/src/main/java/com/sheep/ezloan/lawyer/storage/implement/ReviewJpaRepository.java
Labels: bug

#52 CD
  lawyer/lawyer-api/build.gradle
  lawyer/lawyer-api/src/main/java/com/sheep/ezloan/lawyer/api/controller/LawyerController.java
  lawyer/lawyer-api/src/main/java/com/sheep/ezloan/lawyer/api/dto/CreateLawyerRequestDto.java
  lawyer/lawyer-api/src/main/java/com/sheep/ezloan/lawyer/api/dto/LawyerResponse.java
  lawyer/lawyer-domain/src/main/java/com/sheep/ezloan/lawyer/domain/model/Lawyer.java
  lawyer/lawyer-domain/src/main/java/com/sheep/ezloan/lawyer/domain/repository/LawyerRepository.java
  lawyer/lawyer-domain/src/main/java/com/sheep/ezloan/lawyer/domain/service/LawyerService.java
  lawyer/lawyer-domain/src/test/java/com/sheep/ezloan/lawyer/domain/LawyerServiceTest.java
  lawyer/lawyer-storage/src/main/java/com/sheep/ezloan/lawyer/storage/entity/LawyerEntity.java
  lawyer/lawyer-storage/src/main/java/com/sheep/ezloan/lawyer/storage/implement/LawyerCustomRepository.java
  lawyer/lawyer-storage/src/main/java/com/sheep/ezloan/lawyer/storage/implement/LawyerJpaRepository.java
  lawyer/lawyer-storage/src/main/java/com/sheep/ezloan/lawyer/storage/implement/LawyerJpaRepositoryImpl.java
  lawyer/lawyer-storage/src/main/java/com/sheep/ezloan/lawyer/storage/implement/LawyerRepositoryAdapter.java
  lawyer/lawyer-storage/src/main/java/com/sheep/ezloan/lawyer/storage/implement/ReviewJpaRepository.java
Labels: bug

#55 Hotfix contract user bug fix
  contact/clients/client-user/build.gradle
  contact/clients/client-user/src/main/java/com/sheep/ezloan/contact/client/user/RoleType.java
  contact/clients/client-user/src/main/java/com/sheep/ezloan/contact/client/user/UserClient.java
  contact/clients/client-user/src/main/java/com/sheep/ezloan/contact/client/user/UserConfig.java
  contact/clients/client-user/src/main/java/com/sheep/ezloan/contact/client/user/UserResponseDto.java
  contact/clients/client-user/src/main/resources/client-user.yml
  contact/contact-domain/build.gradle
  contact/contact-domain/src/main/java/com/sheep/ezloan/contact/domain/service/ContractService.java
  settings.gradle
Labels: bug, setting

#58 Feat contract s3
  contact/contact-api/build.gradle
  contact/contact-api/src/main/java/com/sheep/ezloan/contact/api/controller/ContractController.java
  contact/contact-api/src/main/java/com/sheep/ezloan/contact/api/controller/dto/ContractDto.java
  contact/contact-api/src/main/resources/application.yml
  contact/contact-domain/src/main/java/com/sheep/ezloan/contact/domain/fileManager/FileManagerInterface.java
  contact/contact-domain/src/main/java/com/sheep/ezloan/contact/domain/model/S3Result.java
  contact/contact-domain/src/main/java/com/sheep/ezloan/contact/domain/service/ContractService.java
  contact/s3/build.gradle
  contact/s3/src/main/java/com/sheep/ezloan/s3/config/AmazonS3Config.java
  contact/s3/src/main/java/com/sheep/ezloan/s3/config/FileConfig.java
  contact/s3/src/main/java/com/sheep/ezloan/s3/model/S3.java
  contact/s3/src/main/java/com/sheep/ezloan/s3/model/S3Delete.java
  contact/s3/src/main/java/com/sheep/ezloan/s3/service/AmazonS3Service.java
  contact/s3/src/main/resources/s3.yml
  docker-compose.yml
  settings.gradle
Labels: feat

#57 feat: lawyer client user
  lawyer/client-user/build.gradle
  lawyer/client-user/src/main/java/com/sheep/ezloan/lawyer/client/user/FeignUserClient.java
  lawyer/client-user/src/main/java/com/sheep/ezloan/lawyer/client/user/UserClientAdapter.java
  lawyer/client-user/src/main/java/com/sheep/ezloan/lawyer/client/user/UserClientConfig.java
  lawyer/client-user/src/main/resources/lawyer-client-user.yml
  lawyer/lawyer-api/build.gradle
  lawyer/lawyer-api/src/main/java/com/sheep/ezloan/lawyer/api/controller/LawyerController.java
  lawyer/lawyer-api/src/main/resources/application.yml
  lawyer/lawyer-domain/src/main/java/com/sheep/ezloan/lawyer/domain/client/UserClient.java
  lawyer/lawyer-domain/src/main/java/com/sheep/ezloan/lawyer/domain/repository/LawyerRepository.java
  lawyer/lawyer-domain/src/main/java/com/sheep/ezloan/lawyer/domain/service/LawyerService.java
  lawyer/lawyer-storage/src/main/java/com/sheep/ezloan/lawyer/storage/implement/LawyerJpaRepository.java
  lawyer/lawyer-storage/src/main/java/com/sheep/ezloan/lawyer/storage/implement/LawyerJpaRepositoryImpl.java
  lawyer/lawyer-storage/src/main/java/com/sheep/ezloan/lawyer/storage/implement/LawyerRepositoryAdapter.java
  lawyer/lawyer-storage/src/main/resources/lawyer-storage.yml
  settings.gradle
  user/user-api/src/main/java/com/sheep/ezloan/user/api/ClientController.java
Labels: feat
